-- CreateTable
CREATE TABLE "public"."stripe_events" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "stripe_event_id" TEXT NOT NULL,
    "event_type" TEXT NOT NULL,
    "livemode" BOOLEAN NOT NULL,
    "api_version" TEXT,
    "object_id" TEXT,
    "payload" JSONB NOT NULL,
    "processed_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "stripe_events_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "stripe_events_stripe_event_id_key" UNIQUE ("stripe_event_id")
);

-- CreateTable
CREATE TABLE "public"."invoice_payments" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "stripe_invoice_id" TEXT,
    "stripe_payment_intent_id" TEXT,
    "stripe_charge_id" TEXT,
    "customer_email" TEXT,
    "currency" TEXT,
    "amount_paid" BIGINT,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "paid_at" TIMESTAMPTZ,
    "raw_source" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "invoice_payments_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "invoice_payments_status_check" CHECK ("status" IN ('pending', 'paid', 'failed', 'refunded', 'unknown'))
);

-- CreateIndex
CREATE INDEX "stripe_events_event_type_idx" ON "public"."stripe_events"("event_type");

-- CreateIndex
CREATE INDEX "stripe_events_object_id_idx" ON "public"."stripe_events"("object_id");

-- CreateIndex
CREATE UNIQUE INDEX "invoice_payments_stripe_invoice_id_key" ON "public"."invoice_payments"("stripe_invoice_id") WHERE "stripe_invoice_id" IS NOT NULL;

-- CreateIndex
CREATE UNIQUE INDEX "invoice_payments_stripe_payment_intent_id_key" ON "public"."invoice_payments"("stripe_payment_intent_id") WHERE "stripe_payment_intent_id" IS NOT NULL;

-- CreateIndex
CREATE UNIQUE INDEX "invoice_payments_stripe_charge_id_key" ON "public"."invoice_payments"("stripe_charge_id") WHERE "stripe_charge_id" IS NOT NULL;

-- CreateIndex
CREATE INDEX "invoice_payments_customer_email_idx" ON "public"."invoice_payments"("customer_email");

-- CreateIndex
CREATE INDEX "invoice_payments_status_idx" ON "public"."invoice_payments"("status");

-- CreateIndex
CREATE INDEX "invoice_payments_paid_at_idx" ON "public"."invoice_payments"("paid_at" DESC);

-- CreateFunction
CREATE OR REPLACE FUNCTION "public"."set_invoice_payments_updated_at"()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW."updated_at" = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

-- CreateTrigger
DROP TRIGGER IF EXISTS "trg_invoice_payments_updated_at" ON "public"."invoice_payments";

CREATE TRIGGER "trg_invoice_payments_updated_at"
BEFORE UPDATE ON "public"."invoice_payments"
FOR EACH ROW
EXECUTE FUNCTION "public"."set_invoice_payments_updated_at"();
